# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestApp

  # Crashlytics
  #pod 'Fabric'
  #pod 'Crashlytics'
  
  # Facebook SDK
  #pod 'FBSDKCoreKit'
  #pod 'FBSDKShareKit'
  #pod 'FBSDKLoginKit'

  # Networking
  pod 'Alamofire', '~> 4.4.0'
  #pod 'ReachabilitySwift', '~> 3'

  # Database
  #pod 'FMDB'
  #pod 'ObjectMapper', '~> 2.2.6'

  # Utility
  #pod 'Kingfisher', '~> 3.6.2'
  #pod 'SwiftDate', '~> 4.1.1'
  #pod 'NibDesignable', '~> 3.0.0'
  #pod 'NVActivityIndicatorView'
  #pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

  # Static Resource Mapper
  #pod 'R.swift'

  # Log / Debugging
  #pod 'XCGLogger', '~> 5.0.1'

  #Social
  #pod 'LinkedinSwift', '~> 1.6.6'
  #pod 'Google/SignIn'

  #pod 'GoogleMaps'
  #pod 'GooglePlaces'

  target 'TestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
